ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'REVIEWING';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'EDITED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'PUBLISHED';

ALTER TABLE "OrderRequest"
ADD COLUMN IF NOT EXISTS "orderNumber" TEXT,
ADD COLUMN IF NOT EXISTS "dedupeKey" TEXT,
ADD COLUMN IF NOT EXISTS "musicEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "musicChoice" TEXT,
ADD COLUMN IF NOT EXISTS "musicUrl" TEXT,
ADD COLUMN IF NOT EXISTS "photographer" JSONB,
ADD COLUMN IF NOT EXISTS "rejectionReason" TEXT,
ADD COLUMN IF NOT EXISTS "publishedInvitationCode" TEXT,
ADD COLUMN IF NOT EXISTS "submittedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX IF NOT EXISTS "OrderRequest_orderNumber_key" ON "OrderRequest"("orderNumber");
CREATE UNIQUE INDEX IF NOT EXISTS "OrderRequest_dedupeKey_key" ON "OrderRequest"("dedupeKey");
CREATE INDEX IF NOT EXISTS "OrderRequest_submittedAt_idx" ON "OrderRequest"("submittedAt");
